//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeuralNetwork.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NeuralNetwork.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date,Open,High,Low,Close,Volume
        ///6-Mar-13,23.14,23.74,23.04,23.52,388945
        ///5-Mar-13,22.16,23.65,22.14,22.98,411446
        ///4-Mar-13,22.45,22.45,20.94,22.10,310952
        ///1-Mar-13,20.85,22.49,20.81,22.45,378556
        ///28-Feb-13,21.93,22.22,20.59,20.98,340948
        ///27-Feb-13,20.58,21.76,20.55,21.51,171197
        ///26-Feb-13,20.75,20.91,20.33,20.63,50308
        ///25-Feb-13,21.06,21.06,20.61,20.62,95037
        ///22-Feb-13,20.90,21.18,20.73,21.06,101963
        ///21-Feb-13,20.76,21.00,20.70,20.85,88310
        ///20-Feb-13,20.99,21.10,20.65,20.80,74045
        ///19-Feb-13,21.13,21.13,20.70,20.94,693 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string epam {
            get {
                return ResourceManager.GetString("epam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date,Open,High,Low,Close,Volume
        ///6-Mar-13,841.02,844.00,828.81,831.38,2869235
        ///5-Mar-13,828.93,840.15,828.90,838.60,4045034
        ///4-Mar-13,805.30,822.84,805.00,821.50,2776185
        ///1-Mar-13,797.80,807.14,796.15,806.19,2175425
        ///28-Feb-13,801.10,806.99,801.03,801.20,2265874
        ///27-Feb-13,794.80,804.75,791.11,799.78,2028515
        ///26-Feb-13,795.00,795.95,784.40,790.13,2205059
        ///25-Feb-13,802.30,808.41,790.49,790.77,2307008
        ///22-Feb-13,799.26,801.25,793.80,799.71,2054050
        ///21-Feb-13,798.00,805.45,791.22,795.53,3511036
        ///20-Feb-13,805.30,808.97, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string goog {
            get {
                return ResourceManager.GetString("goog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date,Open,High,Low,Close,Volume
        ///6-Mar-13,38.80,39.04,38.70,39.02,11647032
        ///5-Mar-13,38.98,39.00,38.56,38.68,13244475
        ///4-Mar-13,38.60,38.82,38.45,38.82,9934533
        ///1-Mar-13,38.49,38.79,38.49,38.70,13727554
        ///28-Feb-13,38.47,38.97,38.42,38.72,19011794
        ///27-Feb-13,38.03,38.54,37.92,38.45,14277317
        ///26-Feb-13,37.95,38.19,37.78,38.11,15771057
        ///25-Feb-13,38.56,38.72,37.72,37.72,15880343
        ///22-Feb-13,37.76,38.52,37.71,38.52,20102895
        ///21-Feb-13,37.62,37.79,37.43,37.71,14137170
        ///20-Feb-13,37.70,37.88,37.41,37.73,12949360
        ///19-Feb-13,37 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ko {
            get {
                return ResourceManager.GetString("ko", resourceCulture);
            }
        }
    }
}
